let Dataes = [
  {
    id: 1,
    username: "admin",
    email: "admin@somemail.com",
    ip: "::1",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:01",
    confirmation: "Confirmed",
  },
  {
    id: 2,
    username: "officer",
    email: "admin@somemail.com",
    ip: "::2",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:02",
    confirmation: "Confirmed",
  },
  {
    id: 3,
    username: "admin",
    email: "admin@somemail.com",
    ip: "::3",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:03",
    confirmation: "Confirmed",
  },
  {
    id: 4,
    username: "officer",
    email: "admin@somemail.com",
    ip: "::4",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:04",
    confirmation: "Confirmed",
  },
  {
    id: 5,
    username: "admin",
    email: "admin@somemail.com",
    ip: "::5",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:05",
    confirmation: "Confirmed",
  },
  {
    id: 6,
    username: "officer",
    email: "admin@somemail.com",
    ip: "::6",
    time: "27-Nov-20 08:30",
    login: "27-Nov-20 09:06",
    confirmation: "Confirmed",
  },
];

export default Dataes;
